image::https://travis-ci.org/plafue/arc42-template-archetype.svg?branch=master[Build Status, link="https://travis-ci.org/plafue/arc42-template-archetype"]

== arc42-Template Maven Archetype

This is a maven archetype that can aid including the arc42 software architecture template into existing maven projects. The approach here is to use open, "diffable" artifacts (AsciiDoc documents, Shaape diagrams) to ease working with the documentation with developer tools, as well as being able to export to non-technical user friendly formats. Of course you can use other supporting tools or formats if you wish so.

The more generic, verbose asciidoc "golden-master" template is used here, to also help newcomers to find their way in the template structure.

== Usage

At the moment you need to clone/download this project and install it locally (someday it will make it to maven central) :)

[source,bash]
mvn install

Once the archetype is available in your local maven repository, you can generate a new maven module in a directory of your choice, as you would usually do throught the maven archetype plugin:

[source,bash]
mvn archetype:generate                                  \
  -DarchetypeGroupId=org.plafue.arc                     \
  -DarchetypeArtifactId=arc42-template-archetype        \
  -DarchetypeVersion=1.0-SNAPSHOT                       \

An interactive prompt will ask for your project's groupId, artifactId and version. Once you confirm all your inputs a new project with the following scructure will be generated:

[source,bash]
artifactId
├── pom.xml
└── src
    ├── assembly
    │   └── assembly.xml                          <--- Information regarding the final zip artifact
    └── docs
        └── arc42
            ├── 01_introduction_and_goals.adoc
           ...
            ├── 12_glossary.adoc
            ├── about-arc42.adoc
            ├── appendix-contributing.adoc
            ├── appendix-examples.adoc
            ├── appendix-practitioner.adoc
            ├── appendix-references.adoc
            ├── arc42-template.adoc
            ├── config.adoc
            ├── images                            <--- Automagically rendered Shape diagrams will be stored here.
            │   └── arc42-logo.png
            ├── template-blackbox-long.adoc
            ├── template-blackbox-short.adoc
            └── template-whitebox.adoc

You can test your freshly created maven module by running

[source,bash]
mvn process-resources generate-resources
    \                 \ This phase generates a zip file on target, with the contents of target/generated-docs
     \ This phase renders the html version of your adoc files under target/generated-docs

=== Nanos gigantum humeris insidentes

This piece of software is in no way affiliated with arc42.org but it reuses it's core artifact (without necessarily extending it).
The arc42 template is distributed under the MIT Liscense (see https://github.com/arc42/arc42-template).

The POM of the generated project is also preconfigured with the awesome http://asciidoctor.org/news/2014/08/23/asciidoctor-maven-plugin-1-5-0-released/[asciidoctor-maven-plugin],
support of Shaape diagrams (thanks to https://github.com/asciidoctor/asciidoctor-diagram[asciidoctor-diagram]), as well as the maven assembly plugin to package a HTML-Rendered version of the documentation in a zip file (for later upload or distribution).

IMPORTANT: If you wish to use the Shaape rendering support, you need to have Shaape installed locally.


=== Quick reference

* https://github.com/christiangoltz/shaape[Shaape] (Download README.html!)
* http://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer's Guide]

=== TO-DOs / Other ideas:

* Get this to maven central or similarly well known repository - if one has to install this manually first there is not much more benefit from it.
* Use Maven Release plugin/git flow
* Provide both, an english as well as a german version (configuration parameter when generating, maybe?).
  - Or rather go with convention over configuration and use the user locale maybe?
  - There is some denglisch going on in there - maybe support arc42 by cleaning up a little?.
* Help the arc42 fellows to provide the templates as a maven artifact for easier version management.
* Reuse groupId, artifactId (maybe other parameters) within the template (for titles or the like).
* Maybe provide more flexibility in the type of output (Or maybe just focus on html at the moment?)

''''
Bugs, pull requests, ideas... aaaaaaallll welcome.
